# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
# SPDX-License-Identifier: MIT

[workspace]
members = [
  "pub-sub-service",
  "samples/chariott-publisher",
  "samples/chariott-subscriber",
  "samples/common",
  "samples/simple-publisher",
  "samples/simple-subscriber"
]

[workspace.dependencies]
async-std = "1"
async-trait = "0.1.64"
ctrlc = { version = "3.0", features = ["termination"] }
env_logger = "0.10"
futures = "0.3"
log = "^0.4"
paho-mqtt = "0.12"
prost = "0.11"
prost-types = "0.11"
serde_json = "^1.0"
strum = "0.24"
strum_macros = "0.25"
tokio = { version = "1.18.0", features = ["time"] }
tonic = "0.9"
tonic-build = "0.9.2"
tonic-reflection = "0.6"
url = "2.2"
uuid = "1.3.0"