#
# Subscriber Settings
#

# The IP address and port number that the publisher service listens on for requests.
# Only needed for the simple subscriber example.
# Example: "0.0.0.0:80"
publisher_authority: <<value>>

# The URL that the Chariott service listens on for requests.
# Only needed for the chariott subscriber example.
# Example: "http://0.0.0.0:4243"
chariott_url: <<value>>
