#
# Constants Configuration
#

### Communication Constants

# Pub Sub Service topic deletion message.
topic_deletion_message: "TOPIC DELETED"

# Constant for gRPC kind.
grpc_kind: "grpc+proto"

# Constant for mqtt kind.
mqtt_v5_kind: "mqtt_v5"

# Constant for the Pub Sub service API reference.
pub_sub_reference: "pubsub.v1.pubsub.proto"

# Retry interval for connections.
retry_interval_secs: 5

###

#
# Pub Sub Service Settings
#

### Standalone Settings

# The IP address and port number that the Pub Sub Service listens on for requests.
# Example: "0.0.0.0:50051"
pub_sub_authority: "0.0.0.0:50051"

# The URI of the messaging service used to facilitate publish and subscribe functionality.
# Example: "mqtt://0.0.0.0:1883"
messaging_uri: "mqtt://0.0.0.0:1883"

###
