@startuml delete topic sequence diagram
title Delete Topic Sequence Diagram
autonumber
activate Publisher
participant PS_Service
activate Broker
activate Subscriber

Publisher -> Broker : data
Broker -> Subscriber : data
Publisher ->x Broker : data
Publisher -> PS_Service : DeleteTopic(topic)
activate PS_Service
PS_Service -> PS_Service : topic subs == 0?
activate PS_Service
PS_Service -> Broker : publish PubSubAction::DELETE(topic) if any
deactivate PS_Service
PS_Service --> Publisher : ack
deactivate PS_Service
Broker -> Subscriber : TOPIC DELETED on topic
destroy Publisher
Subscriber -->x Broker : disconnect/unsubscribe(topic)
deactivate Subscriber

@enduml