@startuml pubsub chariott component diagram
component "Chariott" as chariott

chariott -right- service_discovery.proto

component "Pub Sub Service" as ps_service

ps_service -right- pubsub.proto
ps_service -down-> publisher.proto
ps_service -up-> service_discovery.proto

component "Publisher" as pub

pub -up-> service_discovery.proto
pub -left-> pubsub.proto
pub -down- publisher.proto
pub -down- sample_publisher.proto

component "Subscriber" as sub

sub -up-> service_discovery.proto
sub -down-> sample_publisher.proto

[ps_service] <--down--> [Broker]
[pub] -down-> [Broker]
[sub] -down-> [Broker]

@enduml