@startuml pubsub component diagram
component "Publisher" as pub

pub -up- publisher.proto
pub -up- sample_publisher.proto
pub -> pubsub.proto

component "Pub Sub Service" as ps_service

ps_service -left- pubsub.proto
ps_service -up-> publisher.proto

component "Subscriber" as sub

sub -up-> sample_publisher.proto

[pub] -down-> [Broker]
[ps_service] <-down-> [Broker]
[sub] <-down- [Broker]

@enduml